spring:
  datasource:
    url: jdbc:mysql://root:dRLzf8dSGOnL3Ui32KCD@containers-us-west-83.railway.app:5975/railway
    username: root
    password: dRLzf8dSGOnL3Ui32KCD
    name: railway
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB

  sql:
    init:
      mode: always

server:
  max-http-header-size: 10MB

