spring:
  datasource:
    url: mysql://root:dRLzf8dSGOnL3Ui32KCD@containers-us-west-83.railway.app:5975/railway
    username: root
    password: dRLzf8dSGOnL3Ui32KCD
    name: railway

  sql:
    init:
      mode: always